version: "3"
services:
  db:
    image: mysql:8.0
    container_name: sistemas-arquivos-virtual_mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: user
      MYSQL_PASSWORD: usersecret
      MYSQL_DATABASE: sistemas-arquivos-virtuais
    volumes:
      - "./db:/var/lib/mysql"
    ports:
      - 3307:3306
